import rtconfig

from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
src += + Glob('Src/*.c')

CPPDEFINES=[]
CPPPATH = [cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
